import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import SessionProvider from "@/components/SessionProvider";
import { getCurrentUser } from "@/lib/session";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next in Live",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SessionProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header user={currentUser} />
            <div className="max-w-5xl mx-auto">{children}</div>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
